# 默认配置
spring:
  profiles:
    active: dev  # runtime java -jar xxx.jar --spring.profiles.active=test
liquibase:
  enabled: true
  drop-first: true
  change-log: classpath:/dbmigraions/changelog.xml
---
# 开发配置
server:
  port: 8000
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
---
# 测试配置
server:
  port: 8001
spring:
  profiles: test
---
# 生产配置
server:
  port: 8002
spring:
  profiles: prod
